# Generated by Django 3.1.1 on 2020-10-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='time_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.CharField(max_length=20)),
                ('closing_time', models.CharField(max_length=20)),
                ('date', models.CharField(default='no date', max_length=20)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.ration_shop_tb')),
            ],
        ),
        migrations.CreateModel(
            name='shop_stock_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice', models.IntegerField()),
                ('wheat', models.IntegerField()),
                ('kerosene', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('rava', models.IntegerField()),
                ('shop_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Admin.ration_shop_tb')),
            ],
        ),
        migrations.CreateModel(
            name='product_allot_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice', models.CharField(max_length=20)),
                ('wheat', models.CharField(max_length=20)),
                ('kerosene', models.CharField(max_length=20)),
                ('sugar', models.CharField(max_length=20)),
                ('rava', models.CharField(max_length=20)),
                ('date_of_allocation', models.CharField(max_length=20)),
                ('date_for_collecting', models.CharField(max_length=20)),
                ('time_for_collecting', models.CharField(max_length=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer_tb')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.purchase_request_tb')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.ration_shop_tb')),
            ],
        ),
    ]
