# Generated by Django 3.1.1 on 2020-10-02 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ration_Shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop_stock_tb',
            old_name='wheat',
            new_name='aatta',
        ),
    ]
