# Generated by Django 3.1.1 on 2020-10-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ration_Shop', '0002_auto_20201003_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_allot_tb',
            old_name='wheat',
            new_name='aatta',
        ),
    ]
