# Generated by Django 3.1.1 on 2020-10-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ration_Shop', '0003_auto_20201003_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_allot_tb',
            name='total_price',
            field=models.CharField(default='000', max_length=20),
        ),
    ]
