# Generated by Django 3.1.1 on 2020-10-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ration_Shop', '0005_auto_20201003_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_allot_tb',
            name='total_price',
            field=models.IntegerField(default='0'),
        ),
    ]
