# Generated by Django 3.1.1 on 2020-10-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ration_Shop', '0006_auto_20201003_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_allot_tb',
            old_name='rava',
            new_name='wheat',
        ),
        migrations.RenameField(
            model_name='shop_stock_tb',
            old_name='rava',
            new_name='wheat',
        ),
    ]
