# Generated by Django 3.1.1 on 2020-10-10 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_ration_shop_tb_address'),
        ('Ration_Shop', '0007_auto_20201003_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_shortage_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice', models.IntegerField()),
                ('aatta', models.IntegerField()),
                ('kerosene', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('wheat', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.ration_shop_tb')),
            ],
        ),
    ]
