# Generated by Django 3.1.1 on 2020-11-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ration_Shop', '0008_product_shortage_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_allot_tb',
            name='aatta',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product_allot_tb',
            name='kerosene',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product_allot_tb',
            name='rice',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product_allot_tb',
            name='sugar',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product_allot_tb',
            name='wheat',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product_shortage_tb',
            name='aatta',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product_shortage_tb',
            name='kerosene',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product_shortage_tb',
            name='rice',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product_shortage_tb',
            name='sugar',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product_shortage_tb',
            name='wheat',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='shop_stock_tb',
            name='aatta',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='shop_stock_tb',
            name='kerosene',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='shop_stock_tb',
            name='rice',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='shop_stock_tb',
            name='sugar',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='shop_stock_tb',
            name='wheat',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
