# Generated by Django 3.1.1 on 2020-11-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ration_Shop', '0009_auto_20201121_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_allot_tb',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
