# Generated by Django 3.1.1 on 2023-10-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ration_Shop', '0010_auto_20201123_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_stock_tb',
            name='aatta',
        ),
        migrations.RemoveField(
            model_name='shop_stock_tb',
            name='kerosene',
        ),
        migrations.RemoveField(
            model_name='shop_stock_tb',
            name='rice',
        ),
        migrations.RemoveField(
            model_name='shop_stock_tb',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='shop_stock_tb',
            name='wheat',
        ),
    ]
