# Generated by Django 3.1.1 on 2023-10-06 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_auto_20201125_0149'),
        ('Ration_Shop', '0011_auto_20201128_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_stock_tb',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Admin.admin_stock_tb'),
        ),
        migrations.AddField(
            model_name='shop_stock_tb',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='shop_stock_tb',
            name='shop_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Admin.ration_shop_tb'),
        ),
    ]
