# Generated by Django 3.1.1 on 2023-10-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ration_Shop', '0013_auto_20201128_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation_tb',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
