# Generated by Django 3.1.1 on 2023-09-19 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_auto_20201125_0149'),
        ('Ration_Shop', '0014_allocation_tb_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_shortage_tb',
            name='aatta',
        ),
        migrations.RemoveField(
            model_name='product_shortage_tb',
            name='kerosene',
        ),
        migrations.RemoveField(
            model_name='product_shortage_tb',
            name='rice',
        ),
        migrations.RemoveField(
            model_name='product_shortage_tb',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='product_shortage_tb',
            name='wheat',
        ),
        migrations.CreateModel(
            name='product_required_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.admin_stock_tb')),
                ('shortage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ration_Shop.product_shortage_tb')),
            ],
        ),
    ]
