# Generated by Django 3.1.1 on 2023-09-07 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ration_Shop', '0015_auto_20201202_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_shortage_tb',
            name='allocation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ration_Shop.product_allot_tb'),
        ),
    ]
