# Generated by Django 3.1.1 on 2023-09-07 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_customer_tb_aadhaar_number'),
        ('Ration_Shop', '0017_auto_20201204_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.purchase_request_tb')),
            ],
        ),
    ]
