# Generated by Django 3.1.1 on 2023-09-07 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_customer_tb_aadhaar_number'),
        ('Ration_Shop', '0018_notification_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_tb',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Customer.customer_tb'),
        ),
    ]
