# Generated by Django 3.1.1 on 2023-09-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ration_Shop', '0019_notification_tb_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_tb',
            name='status',
            field=models.CharField(default='unread', max_length=20),
        ),
    ]
