# Generated by Django 3.1.1 on 2023-09-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ration_Shop', '0020_auto_20210102_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_tb',
            name='datetime',
            field=models.CharField(default='no date', max_length=20),
        ),
    ]
