# Generated by Django 3.1.1 on 2020-10-02 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_stock_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='admin_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='card_category_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='district_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ration_shop_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_number', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('district_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Admin.district_tb')),
            ],
        ),
        migrations.CreateModel(
            name='state_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='stock_allot_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice', models.IntegerField()),
                ('wheat', models.IntegerField()),
                ('kerosene', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('rava', models.IntegerField()),
                ('date', models.CharField(default='no date', max_length=20)),
                ('shop_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Admin.ration_shop_tb')),
            ],
        ),
        migrations.AddField(
            model_name='ration_shop_tb',
            name='state_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Admin.state_tb'),
        ),
        migrations.AddField(
            model_name='district_tb',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.state_tb'),
        ),
    ]
