# Generated by Django 3.1.1 on 2020-10-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_allot_tb',
            old_name='wheat',
            new_name='aatta',
        ),
    ]
