# Generated by Django 3.1.1 on 2020-10-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_auto_20201003_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_stock_tb',
            name='blue_price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='admin_stock_tb',
            name='pink_price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='admin_stock_tb',
            name='white_price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='admin_stock_tb',
            name='yellow_price',
            field=models.IntegerField(default='0'),
        ),
    ]
