# Generated by Django 3.1.1 on 2020-10-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_auto_20201003_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_allot_tb',
            old_name='rava',
            new_name='wheat',
        ),
    ]
