# Generated by Django 3.1.1 on 2020-10-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_auto_20201003_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='ration_shop_tb',
            name='address',
            field=models.CharField(default='no address', max_length=100),
        ),
    ]
