# Generated by Django 3.1.1 on 2020-10-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_ration_shop_tb_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_allot_tb',
            name='month',
            field=models.CharField(default='no month', max_length=20),
        ),
        migrations.AddField(
            model_name='stock_allot_tb',
            name='year',
            field=models.CharField(default='no year', max_length=20),
        ),
    ]
