# Generated by Django 3.1.1 on 2020-10-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_auto_20201011_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_allot_tb',
            name='status',
            field=models.CharField(default='allotted', max_length=20),
        ),
    ]
