# Generated by Django 3.1.1 on 2020-11-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_stock_allot_tb_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_stock_tb',
            name='blue_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='admin_stock_tb',
            name='pink_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='admin_stock_tb',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='admin_stock_tb',
            name='white_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='admin_stock_tb',
            name='yellow_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='stock_allot_tb',
            name='aatta',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='stock_allot_tb',
            name='kerosene',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='stock_allot_tb',
            name='rice',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='stock_allot_tb',
            name='sugar',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='stock_allot_tb',
            name='wheat',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
