# Generated by Django 3.1.1 on 2020-11-24 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_auto_20201121_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_allot_tb',
            name='aatta',
        ),
        migrations.RemoveField(
            model_name='stock_allot_tb',
            name='kerosene',
        ),
        migrations.RemoveField(
            model_name='stock_allot_tb',
            name='rice',
        ),
        migrations.RemoveField(
            model_name='stock_allot_tb',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='stock_allot_tb',
            name='wheat',
        ),
    ]
