# Generated by Django 3.1.1 on 2020-11-24 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_auto_20201125_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='allotted_product_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(decimal_places=2, max_digits=8)),
                ('allot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.stock_allot_tb')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.admin_stock_tb')),
            ],
        ),
    ]
