# Generated by Django 3.1.1 on 2020-11-24 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_allotted_product_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotted_product_tb',
            name='allot_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.stock_allot_tb'),
        ),
    ]
