# Generated by Django 3.1.1 on 2021-01-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_customer_tb_aadhaar_number'),
        ('Admin', '0011_auto_20201125_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='reply_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=20)),
                ('status', models.CharField(default='unread', max_length=20)),
                ('complaint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.complaint_tb')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer_tb')),
            ],
        ),
    ]
