# Generated by Django 3.1.1 on 2021-04-03 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_reply_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ration_shop_tb',
            name='state_id',
        ),
    ]
