# Generated by Django 3.1.1 on 2021-04-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_remove_ration_shop_tb_state_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district_tb',
            name='state_id',
        ),
    ]
