# Generated by Django 3.1.1 on 2021-04-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_remove_district_tb_state_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='state_tb',
        ),
    ]
