# Generated by Django 3.1.1 on 2020-10-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20)),
                ('card_owner', models.CharField(max_length=30)),
                ('owner_photo', models.FileField(max_length=30, upload_to='')),
                ('house_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('member_count', models.CharField(max_length=20)),
                ('monthly_income', models.CharField(max_length=20)),
                ('username', models.CharField(default='none', max_length=20)),
                ('password', models.CharField(default='none', max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('card_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.card_category_tb')),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.district_tb')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.ration_shop_tb')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.state_tb')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_request_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='no year', max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer_tb')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.ration_shop_tb')),
            ],
        ),
        migrations.CreateModel(
            name='members_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('relationship', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
                ('income', models.CharField(max_length=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer_tb')),
            ],
        ),
    ]
