# Generated by Django 3.1.1 on 2020-10-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_complaint_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members_tb',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='members_tb',
            name='card_number',
            field=models.CharField(default='no number', max_length=20),
        ),
    ]
