# Generated by Django 3.1.1 on 2020-10-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_auto_20201006_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_tb',
            name='phone',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
