# Generated by Django 3.1.1 on 2020-10-06 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_customer_tb_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members_tb',
            name='card_number',
        ),
        migrations.AddField(
            model_name='members_tb',
            name='customer_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Customer.customer_tb'),
        ),
    ]
