# Generated by Django 3.1.1 on 2020-10-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_auto_20201007_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('credit_card_number', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=20)),
                ('balance', models.CharField(max_length=20)),
            ],
        ),
    ]
