# Generated by Django 3.1.1 on 2020-10-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_payment_tb_purchase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_tb',
            name='aadhaar_number',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
