# Generated by Django 3.1.1 on 2021-01-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_customer_tb_aadhaar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_tb',
            name='adults',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer_tb',
            name='child',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer_tb',
            name='taluk',
            field=models.CharField(default='no taluk', max_length=20),
        ),
        migrations.AddField(
            model_name='customer_tb',
            name='units',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='customer_tb',
            name='ward_number',
            field=models.IntegerField(default=0),
        ),
    ]
