# Generated by Django 3.1.1 on 2021-04-03 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_auto_20210117_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_tb',
            name='state_id',
        ),
    ]
